/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;



import Controller.AlunoDao;

import Controller.ControlAluno;

import Model.AlunosModel;
import Model.Conexao_bd;
import static com.sun.org.apache.xalan.internal.lib.ExsltDatetime.date;
import static com.sun.org.apache.xalan.internal.lib.ExsltDatetime.date;
import static com.sun.org.apache.xalan.internal.lib.ExsltDatetime.date;
import static java.lang.System.in;
import static java.lang.System.out;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;

import java.util.ArrayList;
import java.util.Calendar;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.DateFormatter;
import javax.xml.bind.DatatypeConverter;

/**
 *
 * @author Willian
 */
public class Alunos extends javax.swing.JFrame {
   AlunoDao a;
    /**
     * Creates new form Alunos
     */
    public Alunos() {
    
        initComponents();
        setLocationRelativeTo(null);
        
    
    }
     AlunoDao b = new AlunoDao();

  
    public void CarregarTabela(String aluno){
      try{
        //AlunosModel b = new AlunosModel();
         AlunoDao a = new AlunoDao();
        
         DefaultTableModel modelo = (DefaultTableModel)   this.jTable2.getModel();
         
         modelo.setNumRows(0);
         jTable2.getColumnModel().getColumn(0);
           jTable2.getColumnModel().getColumn(1);
          jTable2.getColumnModel().getColumn(2);
           jTable2.getColumnModel().getColumn(3);
           
        
      
           
           for( AlunosModel r : a.Listar(aluno)){
               modelo.addRow(new Object[]{
                
                   r.getRg(),
                   r.getNome(),
                   r.getSobrenome(),
                   r.getData()
               });
           }
           
               
               //modelo.addRow(a.selecionaAluno(al));
       } catch (Exception ex) {
           Logger.getLogger(Alunos.class.getName()).log(Level.SEVERE, null, ex);
       }
        
    }
    
     public void limparCampos(){
         
         rg1.setText("");
         nome2.setText("");
         sobrenome1.setText("");
         data1.setText("");
     }
     
    public void Salvar() {
  


         String nome = nome2.getText();
         String rg = rg1.getText();
         String sobrenome2 = sobrenome1.getText().trim();
         String dataa =data1.getText();
         
        
        ControlAluno c = new ControlAluno();
       
        c.AlunoControl(nome, sobrenome2, rg,dataa);
       jButton3.setEnabled(true);
       
   }
    
    public void Tab(){
        int linha=0;
  
         String nome = nome2.getText();
         String rg = rg1.getText();
         String sobrenome2 = sobrenome1.getText();
         String dataa=data1.getText().trim();
         
         if(nome.length()>0&&rg.length()>7&&sobrenome2.length()>0&&dataa.length()>0)
         jTable1.setValueAt(rg, linha, 0);
           jTable1.setValueAt(nome, linha, 1);
           jTable1.setValueAt(sobrenome2, linha, 2);
           jTable1.setValueAt(dataa, linha, 3);
           linha+=1;
           
         
    }
    
    
    
    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jPanel10 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        sobrenome1 = new javax.swing.JTextField();
        nome2 = new javax.swing.JTextField();
        jPanel13 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        rg1 = new javax.swing.JFormattedTextField();
        data1 = new javax.swing.JFormattedTextField();
        jButton3 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox<>();
        nome1 = new javax.swing.JTextField();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jFormattedTextField3 = new javax.swing.JFormattedTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        sobrenomedisc = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        saladisc = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        periododisc = new javax.swing.JTextField();
        turmadisc = new javax.swing.JTextField();
        rgdis = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        datadisc = new javax.swing.JTextField();
        nomedisc = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton16 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel8 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        dat = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        sobrenome2 = new javax.swing.JTextField();
        nom1 = new javax.swing.JTextField();
        rg3 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        busca = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        edit = new javax.swing.JButton();
        limpa = new javax.swing.JButton();
        excluir = new javax.swing.JButton();
        rgt = new javax.swing.JFormattedTextField();
        salvar1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jTextField17 = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel24 = new javax.swing.JLabel();
        jTextField18 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jTextField19 = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jSeparator10 = new javax.swing.JSeparator();
        jButton11 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jTextField23 = new javax.swing.JTextField();
        jTextField24 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jTextField28 = new javax.swing.JTextField();
        jTextField29 = new javax.swing.JTextField();
        jTextField30 = new javax.swing.JTextField();
        jTextField31 = new javax.swing.JTextField();
        jTextField32 = new javax.swing.JTextField();
        jTextField33 = new javax.swing.JTextField();
        jTextField34 = new javax.swing.JTextField();
        jTextField35 = new javax.swing.JTextField();
        jTextField36 = new javax.swing.JTextField();
        jTextField37 = new javax.swing.JTextField();
        jTextField38 = new javax.swing.JTextField();
        jTextField25 = new javax.swing.JTextField();
        jTextField39 = new javax.swing.JTextField();
        jTextField40 = new javax.swing.JTextField();
        jTextField41 = new javax.swing.JTextField();
        jTextField42 = new javax.swing.JTextField();
        jTextField43 = new javax.swing.JTextField();
        jTextField44 = new javax.swing.JTextField();
        jTextField26 = new javax.swing.JTextField();
        jTextField45 = new javax.swing.JTextField();
        jTextField46 = new javax.swing.JTextField();
        jTextField47 = new javax.swing.JTextField();
        jTextField48 = new javax.swing.JTextField();
        jTextField49 = new javax.swing.JTextField();
        jTextField27 = new javax.swing.JTextField();
        jTextField50 = new javax.swing.JTextField();
        jTextField51 = new javax.swing.JTextField();
        jTextField52 = new javax.swing.JTextField();
        jTextField53 = new javax.swing.JTextField();
        jTextField54 = new javax.swing.JTextField();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator13 = new javax.swing.JSeparator();
        jSeparator14 = new javax.swing.JSeparator();
        jSeparator15 = new javax.swing.JSeparator();
        jSeparator16 = new javax.swing.JSeparator();
        jPanel11 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jTextField21 = new javax.swing.JTextField();
        jButton12 = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jTextField22 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jButton14 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jLabel37 = new javax.swing.JLabel();
        jSeparator12 = new javax.swing.JSeparator();
        jButton15 = new javax.swing.JButton();
        jPanel15 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Dados do Aluno");
        setResizable(false);

        jTabbedPane1.setBackground(new java.awt.Color(0, 51, 51));
        jTabbedPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTabbedPane1.setForeground(new java.awt.Color(0, 102, 102));
        jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jPanel1.setForeground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("RG");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 35, 30, 20));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 166, 848, -1));

        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 10, 10, 160));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 850, 20));

        jSeparator8.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 10, 160));

        jPanel10.setBackground(new java.awt.Color(204, 204, 255));
        jPanel10.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel10.setEnabled(false);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Sobrenome");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Data Nascimento");

        sobrenome1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sobrenome1ActionPerformed(evt);
            }
        });

        nome2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nome2ActionPerformed(evt);
            }
        });

        jPanel13.setBackground(new java.awt.Color(204, 204, 255));
        jPanel13.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTable1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTable1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTable1.setForeground(new java.awt.Color(0, 102, 51));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "RG", "Nome", "Sobrenome", "Data Nascimento"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(9);
        }

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 760, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Nome");

        try {
            rg1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("########-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        rg1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        try {
            data1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistema/imagens/save_all.png"))); // NOI18N
        jButton3.setText("Salvar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(rg1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(150, 150, 150)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(data1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(14, 14, 14)
                        .addComponent(nome2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(170, 170, 170)
                        .addComponent(jLabel5)
                        .addGap(29, 29, 29)
                        .addComponent(sobrenome1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(68, 68, 68))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rg1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(data1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nome2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sobrenome1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(90, 90, 90)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 510));

        jComboBox2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, 110, -1));

        nome1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nome1ActionPerformed(evt);
            }
        });
        jPanel1.add(nome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, 200, 30));

        jFormattedTextField1.setText("jFormattedTextField1");
        jPanel1.add(jFormattedTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 40, -1, 40));

        jFormattedTextField3.setText("jFormattedTextField3");
        jPanel1.add(jFormattedTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 180, -1, 90));

        jTabbedPane1.addTab("Cadastrar Aluno", jPanel1);

        jPanel2.setLayout(null);

        jPanel14.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel14.setLayout(null);
        jPanel14.add(sobrenomedisc);
        sobrenomedisc.setBounds(650, 30, 180, 31);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("RG");
        jPanel14.add(jLabel8);
        jLabel8.setBounds(20, 30, 40, 31);

        jLabel39.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel39.setText("Sobrenome");
        jPanel14.add(jLabel39);
        jLabel39.setBounds(550, 30, 92, 31);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("Turma");
        jPanel14.add(jLabel16);
        jLabel16.setBounds(570, 270, 70, 31);

        jLabel40.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel40.setText("Sala");
        jPanel14.add(jLabel40);
        jLabel40.setBounds(30, 270, 92, 31);
        jPanel14.add(saladisc);
        saladisc.setBounds(70, 270, 190, 31);

        jLabel38.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel38.setText("Periodo");
        jPanel14.add(jLabel38);
        jLabel38.setBounds(320, 270, 92, 31);
        jPanel14.add(periododisc);
        periododisc.setBounds(390, 270, 140, 31);
        jPanel14.add(turmadisc);
        turmadisc.setBounds(630, 270, 150, 31);
        jPanel14.add(rgdis);
        rgdis.setBounds(50, 30, 190, 31);

        jLabel41.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel41.setText("Disciplina");
        jPanel14.add(jLabel41);
        jLabel41.setBounds(20, 160, 92, 31);

        jLabel42.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel42.setText("Data de Nascimento");
        jPanel14.add(jLabel42);
        jLabel42.setBounds(330, 150, 130, 31);
        jPanel14.add(datadisc);
        datadisc.setBounds(470, 150, 180, 31);
        jPanel14.add(nomedisc);
        nomedisc.setBounds(340, 30, 180, 31);

        jLabel43.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel43.setText("Nome");
        jPanel14.add(jLabel43);
        jLabel43.setBounds(270, 30, 92, 31);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel14.add(jComboBox1);
        jComboBox1.setBounds(90, 160, 130, 30);

        jPanel2.add(jPanel14);
        jPanel14.setBounds(20, 60, 910, 340);

        jButton16.setText("Salvar");
        jPanel2.add(jButton16);
        jButton16.setBounds(90, 433, 110, 30);

        jTabbedPane1.addTab("Cadastrar na Disciplina", jPanel2);

        jPanel3.setLayout(null);
        jPanel3.add(jSeparator1);
        jSeparator1.setBounds(0, 80, 928, 10);

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados do aluno"));
        jPanel8.setLayout(null);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("RG");
        jPanel8.add(jLabel10);
        jLabel10.setBounds(16, 27, 44, 17);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("NOME");
        jPanel8.add(jLabel11);
        jLabel11.setBounds(10, 110, 40, 17);

        dat.setEditable(false);
        dat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datActionPerformed(evt);
            }
        });
        jPanel8.add(dat);
        dat.setBounds(160, 190, 120, 30);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("DATA NASCIMENTO");
        jPanel8.add(jLabel14);
        jLabel14.setBounds(20, 200, 150, 17);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("Turno");
        jPanel8.add(jLabel15);
        jLabel15.setBounds(215, 31, 80, 14);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("SOBRENOME");
        jPanel8.add(jLabel12);
        jLabel12.setBounds(200, 110, 85, 17);

        jTextField10.setEditable(false);
        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });
        jPanel8.add(jTextField10);
        jTextField10.setBounds(270, 20, 150, 30);

        jTextField11.setEditable(false);
        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });
        jPanel8.add(jTextField11);
        jTextField11.setBounds(560, 100, 120, 30);

        jTextField12.setEditable(false);
        jTextField12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField12ActionPerformed(evt);
            }
        });
        jPanel8.add(jTextField12);
        jTextField12.setBounds(570, 20, 66, 30);

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("Turma");
        jPanel8.add(jLabel17);
        jLabel17.setBounds(510, 30, 60, 17);

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel21.setText("Observações");
        jPanel8.add(jLabel21);
        jLabel21.setBounds(560, 200, 87, 17);

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setText("Sala");
        jPanel8.add(jLabel22);
        jLabel22.setBounds(520, 110, 50, 17);

        sobrenome2.setEditable(false);
        sobrenome2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sobrenome2ActionPerformed(evt);
            }
        });
        jPanel8.add(sobrenome2);
        sobrenome2.setBounds(290, 100, 190, 30);

        nom1.setEditable(false);
        nom1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nom1ActionPerformed(evt);
            }
        });
        jPanel8.add(nom1);
        nom1.setBounds(60, 110, 120, 30);

        rg3.setEditable(false);
        rg3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rg3ActionPerformed(evt);
            }
        });
        jPanel8.add(rg3);
        rg3.setBounds(52, 27, 140, 30);

        jTextField16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField16ActionPerformed(evt);
            }
        });
        jPanel8.add(jTextField16);
        jTextField16.setBounds(660, 190, 132, 30);

        jPanel3.add(jPanel8);
        jPanel8.setBounds(20, 110, 860, 300);

        busca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistema/imagens/viewmag.png"))); // NOI18N
        busca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscaActionPerformed(evt);
            }
        });
        jPanel3.add(busca);
        busca.setBounds(240, 40, 70, 31);

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setText("RG");
        jPanel3.add(jLabel19);
        jLabel19.setBounds(10, 40, 30, 30);

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setText("Digite o RG para alterar os dados");
        jPanel3.add(jLabel20);
        jLabel20.setBounds(50, 10, 270, 20);

        edit.setText("Editar");
        edit.setEnabled(false);
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        jPanel3.add(edit);
        edit.setBounds(40, 440, 90, 30);

        limpa.setText("Limpar");
        limpa.setEnabled(false);
        limpa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpaActionPerformed(evt);
            }
        });
        jPanel3.add(limpa);
        limpa.setBounds(420, 440, 80, 30);

        excluir.setText("Excluir");
        excluir.setEnabled(false);
        jPanel3.add(excluir);
        excluir.setBounds(180, 440, 80, 30);

        try {
            rgt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("########-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel3.add(rgt);
        rgt.setBounds(50, 40, 170, 30);

        salvar1.setText("Salvar");
        salvar1.setEnabled(false);
        salvar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvar1ActionPerformed(evt);
            }
        });
        jPanel3.add(salvar1);
        salvar1.setBounds(300, 440, 80, 30);

        jTabbedPane1.addTab("Alterações", jPanel3);

        jPanel4.setLayout(null);

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel23.setText("RG do Aluno:");
        jPanel4.add(jLabel23);
        jLabel23.setBounds(60, 10, 160, 30);
        jPanel4.add(jTextField17);
        jTextField17.setBounds(50, 40, 210, 30);

        jButton8.setText("buscar");
        jPanel4.add(jButton8);
        jButton8.setBounds(280, 40, 80, 30);
        jPanel4.add(jSeparator9);
        jSeparator9.setBounds(0, 80, 930, 10);

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel24.setText("RG");
        jPanel4.add(jLabel24);
        jLabel24.setBounds(360, 110, 60, 20);

        jTextField18.setEditable(false);
        jPanel4.add(jTextField18);
        jTextField18.setBounds(400, 110, 240, 30);

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel25.setText("Aluno");
        jPanel4.add(jLabel25);
        jLabel25.setBounds(20, 110, 60, 20);

        jTextField19.setEditable(false);
        jPanel4.add(jTextField19);
        jTextField19.setBounds(70, 110, 220, 30);

        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel7.setLayout(null);

        jTable3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Sobrenome", "Disciplina", "Nª de Faltas"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane3.setViewportView(jTable3);
        if (jTable3.getColumnModel().getColumnCount() > 0) {
            jTable3.getColumnModel().getColumn(0).setResizable(false);
        }

        jPanel7.add(jScrollPane3);
        jScrollPane3.setBounds(40, 30, 680, 220);

        jPanel4.add(jPanel7);
        jPanel7.setBounds(30, 160, 840, 270);

        jButton9.setText("Editar");
        jPanel4.add(jButton9);
        jButton9.setBounds(170, 450, 80, 30);

        jButton10.setText("Salvar");
        jPanel4.add(jButton10);
        jButton10.setBounds(50, 450, 80, 30);

        jTabbedPane1.addTab("Lançar Frequencias", jPanel4);

        jPanel5.setLayout(null);
        jPanel5.add(jSeparator10);
        jSeparator10.setBounds(0, 60, 930, 10);

        jButton11.setText("Salvar");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton11);
        jButton11.setBounds(810, 440, 100, 30);

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel6.setLayout(null);
        jPanel6.add(jTextField23);
        jTextField23.setBounds(10, 250, 110, 30);

        jTextField24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField24ActionPerformed(evt);
            }
        });
        jPanel6.add(jTextField24);
        jTextField24.setBounds(670, 50, 80, 30);

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel30.setText("Media Final");
        jPanel6.add(jLabel30);
        jLabel30.setBounds(670, 10, 90, 30);

        jLabel32.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel32.setText("Disciplina");
        jPanel6.add(jLabel32);
        jLabel32.setBounds(20, 10, 100, 30);

        jLabel33.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel33.setText("2º Bimestre");
        jPanel6.add(jLabel33);
        jLabel33.setBounds(290, 10, 90, 30);

        jLabel34.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel34.setText("3º Bimestre");
        jPanel6.add(jLabel34);
        jLabel34.setBounds(410, 10, 90, 30);

        jLabel35.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel35.setText("4º Bimestre");
        jPanel6.add(jLabel35);
        jLabel35.setBounds(550, 10, 90, 30);

        jLabel36.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel36.setText("1º Bimestre");
        jPanel6.add(jLabel36);
        jLabel36.setBounds(160, 10, 90, 30);
        jPanel6.add(jTextField28);
        jTextField28.setBounds(670, 100, 80, 30);

        jTextField29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField29ActionPerformed(evt);
            }
        });
        jPanel6.add(jTextField29);
        jTextField29.setBounds(280, 50, 80, 30);
        jPanel6.add(jTextField30);
        jTextField30.setBounds(410, 50, 80, 30);
        jPanel6.add(jTextField31);
        jTextField31.setBounds(540, 50, 80, 30);
        jPanel6.add(jTextField32);
        jTextField32.setBounds(10, 50, 110, 30);
        jPanel6.add(jTextField33);
        jTextField33.setBounds(10, 100, 110, 30);
        jPanel6.add(jTextField34);
        jTextField34.setBounds(150, 50, 80, 30);
        jPanel6.add(jTextField35);
        jTextField35.setBounds(670, 200, 80, 30);
        jPanel6.add(jTextField36);
        jTextField36.setBounds(670, 150, 80, 30);
        jPanel6.add(jTextField37);
        jTextField37.setBounds(410, 100, 80, 30);

        jTextField38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField38ActionPerformed(evt);
            }
        });
        jPanel6.add(jTextField38);
        jTextField38.setBounds(540, 100, 80, 30);
        jPanel6.add(jTextField25);
        jTextField25.setBounds(10, 100, 110, 30);
        jPanel6.add(jTextField39);
        jTextField39.setBounds(150, 100, 80, 30);
        jPanel6.add(jTextField40);
        jTextField40.setBounds(150, 100, 80, 30);
        jPanel6.add(jTextField41);
        jTextField41.setBounds(280, 100, 80, 30);
        jPanel6.add(jTextField42);
        jTextField42.setBounds(280, 150, 80, 30);
        jPanel6.add(jTextField43);
        jTextField43.setBounds(410, 150, 80, 30);
        jPanel6.add(jTextField44);
        jTextField44.setBounds(540, 150, 80, 30);
        jPanel6.add(jTextField26);
        jTextField26.setBounds(10, 150, 110, 30);
        jPanel6.add(jTextField45);
        jTextField45.setBounds(150, 150, 80, 30);
        jPanel6.add(jTextField46);
        jTextField46.setBounds(670, 250, 80, 30);
        jPanel6.add(jTextField47);
        jTextField47.setBounds(280, 200, 80, 30);
        jPanel6.add(jTextField48);
        jTextField48.setBounds(410, 200, 80, 30);
        jPanel6.add(jTextField49);
        jTextField49.setBounds(540, 200, 80, 30);
        jPanel6.add(jTextField27);
        jTextField27.setBounds(10, 200, 110, 30);
        jPanel6.add(jTextField50);
        jTextField50.setBounds(150, 200, 80, 30);
        jPanel6.add(jTextField51);
        jTextField51.setBounds(150, 250, 80, 30);
        jPanel6.add(jTextField52);
        jTextField52.setBounds(280, 250, 80, 30);
        jPanel6.add(jTextField53);
        jTextField53.setBounds(410, 250, 80, 30);
        jPanel6.add(jTextField54);
        jTextField54.setBounds(540, 250, 80, 30);
        jPanel6.add(jSeparator11);
        jSeparator11.setBounds(0, 40, 750, 10);
        jPanel6.add(jSeparator13);
        jSeparator13.setBounds(0, 240, 780, 10);
        jPanel6.add(jSeparator14);
        jSeparator14.setBounds(0, 90, 770, 10);
        jPanel6.add(jSeparator15);
        jSeparator15.setBounds(0, 140, 770, 10);
        jPanel6.add(jSeparator16);
        jSeparator16.setBounds(0, 190, 780, 10);

        jPanel11.setBackground(new java.awt.Color(102, 204, 255));
        jPanel11.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 776, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
        );

        jPanel6.add(jPanel11);
        jPanel11.setBounds(0, 0, 780, 40);

        jPanel5.add(jPanel6);
        jPanel6.setBounds(20, 110, 780, 320);
        jPanel5.add(jLabel28);
        jLabel28.setBounds(60, 80, 180, 20);
        jPanel5.add(jTextField21);
        jTextField21.setBounds(60, 20, 210, 30);

        jButton12.setText("buscar");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton12);
        jButton12.setBounds(290, 20, 90, 30);

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel29.setText("RG");
        jPanel5.add(jLabel29);
        jLabel29.setBounds(14, 20, 30, 30);

        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel31.setText("Aluno");
        jPanel5.add(jLabel31);
        jLabel31.setBounds(10, 70, 70, 30);

        jPanel12.setBackground(new java.awt.Color(153, 102, 255));
        jPanel12.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 916, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 56, Short.MAX_VALUE)
        );

        jPanel5.add(jPanel12);
        jPanel12.setBounds(0, 0, 920, 60);

        jTabbedPane1.addTab("Lançar Notas", jPanel5);

        jPanel9.setLayout(null);
        jPanel9.add(jTextField22);
        jTextField22.setBounds(70, 30, 200, 30);

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel27.setText("Observações");
        jPanel9.add(jLabel27);
        jLabel27.setBounds(40, 320, 130, 20);

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Aluno", "Media Final", "Frequência", "Resultado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Float.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jTable4);
        if (jTable4.getColumnModel().getColumnCount() > 0) {
            jTable4.getColumnModel().getColumn(0).setResizable(false);
            jTable4.getColumnModel().getColumn(1).setResizable(false);
            jTable4.getColumnModel().getColumn(2).setResizable(false);
            jTable4.getColumnModel().getColumn(3).setResizable(false);
        }

        jPanel9.add(jScrollPane4);
        jScrollPane4.setBounds(30, 90, 650, 190);

        jButton14.setText("Salvar");
        jPanel9.add(jButton14);
        jButton14.setBounds(510, 443, 80, 30);

        jScrollPane5.setViewportView(jTextPane1);

        jPanel9.add(jScrollPane5);
        jScrollPane5.setBounds(30, 360, 450, 120);

        jLabel37.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel37.setText("RG");
        jPanel9.add(jLabel37);
        jLabel37.setBounds(10, 30, 70, 20);
        jPanel9.add(jSeparator12);
        jSeparator12.setBounds(0, 310, 920, 10);

        jButton15.setText("Buscar");
        jPanel9.add(jButton15);
        jButton15.setBounds(290, 30, 80, 30);

        jTabbedPane1.addTab("Medias e Frequências", jPanel9);

        jPanel15.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPanel15KeyReleased(evt);
            }
        });
        jPanel15.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Aluno");
        jPanel15.add(jLabel3);
        jLabel3.setBounds(10, 30, 70, 40);

        jTable2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "RG", "Nome", "Sobrenome", "Data Nasc"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setResizable(false);
            jTable2.getColumnModel().getColumn(1).setResizable(false);
            jTable2.getColumnModel().getColumn(2).setResizable(false);
            jTable2.getColumnModel().getColumn(3).setResizable(false);
        }

        jPanel15.add(jScrollPane2);
        jScrollPane2.setBounds(70, 120, 640, 280);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });
        jPanel15.add(jTextField1);
        jTextField1.setBounds(80, 40, 200, 30);

        jTabbedPane1.addTab("Consultar alunos", jPanel15);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistema/imagens/remover.png"))); // NOI18N
        jButton4.setText("Cancelar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(192, 192, 192))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 937, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 9, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setBounds(0, 0, 962, 622);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11ActionPerformed

    private void datActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_datActionPerformed
 
    private void buscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscaActionPerformed
            
             String nome =rgt.getText().trim();
                
       ArrayList<AlunosModel> a =  b.ListarRG(nome);
        
        
       try {
           if(rgt.getText().length()>0){
            for(AlunosModel d : b.ListarRG(nome)){
                  rg3.setText(d.getRg());
             nom1.setText(d.getNome());
              sobrenome2.setText(d.getSobrenome());
             dat.setText(d.getData());
          }
          }else  {
           JOptionPane.showMessageDialog(null, "insira o RG do aluno", "aviso", JOptionPane.ERROR_MESSAGE);
           }
       } catch (Exception ex) {
           JOptionPane.showMessageDialog(null, "insira o RG do aluno", "aviso", JOptionPane.ERROR_MESSAGE);
       }
        
             edit.setEnabled(true);
             limpa.setEnabled(true);
             excluir.setEnabled(true);
            
             

    }//GEN-LAST:event_buscaActionPerformed

    private void jTextField12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField12ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jTextField38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField38ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField38ActionPerformed

    private void jTextField24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField24ActionPerformed

    private void jTextField29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField29ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField29ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         String nome = nome2.getText();
          Pattern pattern = Pattern.compile("[0123456789]");  
	Matcher matcher = pattern.matcher(nome);  
        if (matcher.find()) {  
            JOptionPane.showMessageDialog(null, "Digite apenas letra", "aviso", JOptionPane.INFORMATION_MESSAGE);
        }
        else{
          Salvar();
              
           Tab();
            limparCampos(); 
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void sobrenome1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sobrenome1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sobrenome1ActionPerformed

    private void sobrenome2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sobrenome2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sobrenome2ActionPerformed

    private void nome1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nome1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nome1ActionPerformed

    private void nome2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nome2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nome2ActionPerformed

    private void jPanel15KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPanel15KeyReleased
            // TODO add your handling code here:
    }//GEN-LAST:event_jPanel15KeyReleased

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
          CarregarTabela(jTextField1.getText());// TODO add your handling code here:
    }//GEN-LAST:event_jTextField1KeyReleased

    private void limpaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpaActionPerformed
           rg3.setText("");
             nom1.setText("");
              sobrenome2.setText("");
             dat.setText("");    // TODO add your handling code here:
    }//GEN-LAST:event_limpaActionPerformed

    private void nom1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nom1ActionPerformed
       
    }//GEN-LAST:event_nom1ActionPerformed

    private void rg3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rg3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rg3ActionPerformed

    private void jTextField16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField16ActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        rg3.setEditable(true);
             nom1.setEditable(true);
              sobrenome2.setEditable(true);
             dat.setEditable(true);
    }//GEN-LAST:event_editActionPerformed

    private void salvar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salvar1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
         dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
     
          DefaultTableModel modelo = (DefaultTableModel) this.jTable1.getModel();
          int index = jTable1.getSelectedRow();
       if(evt.getClickCount()==2){
           jTabbedPane1.setSelectedIndex(1);
          rgdis.setText(modelo.getValueAt(index, 0).toString());
          nomedisc.setText(modelo.getValueAt(index, 1).toString());
          sobrenomedisc.setText(modelo.getValueAt(index, 2).toString());
          datadisc.setText(modelo.getValueAt(index, 3).toString());
       }   
          
           
        
        
        
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Alunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Alunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Alunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Alunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                 new Alunos().setVisible(false);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton busca;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JTextField dat;
    public static javax.swing.JFormattedTextField data1;
    private javax.swing.JTextField datadisc;
    private javax.swing.JButton edit;
    private javax.swing.JButton excluir;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    public javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JFormattedTextField jFormattedTextField3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    public javax.swing.JTabbedPane jTabbedPane1;
    public static javax.swing.JTable jTable1;
    public javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField25;
    private javax.swing.JTextField jTextField26;
    private javax.swing.JTextField jTextField27;
    private javax.swing.JTextField jTextField28;
    private javax.swing.JTextField jTextField29;
    private javax.swing.JTextField jTextField30;
    private javax.swing.JTextField jTextField31;
    private javax.swing.JTextField jTextField32;
    private javax.swing.JTextField jTextField33;
    private javax.swing.JTextField jTextField34;
    private javax.swing.JTextField jTextField35;
    private javax.swing.JTextField jTextField36;
    private javax.swing.JTextField jTextField37;
    private javax.swing.JTextField jTextField38;
    private javax.swing.JTextField jTextField39;
    private javax.swing.JTextField jTextField40;
    private javax.swing.JTextField jTextField41;
    private javax.swing.JTextField jTextField42;
    private javax.swing.JTextField jTextField43;
    private javax.swing.JTextField jTextField44;
    private javax.swing.JTextField jTextField45;
    private javax.swing.JTextField jTextField46;
    private javax.swing.JTextField jTextField47;
    private javax.swing.JTextField jTextField48;
    private javax.swing.JTextField jTextField49;
    private javax.swing.JTextField jTextField50;
    private javax.swing.JTextField jTextField51;
    private javax.swing.JTextField jTextField52;
    private javax.swing.JTextField jTextField53;
    private javax.swing.JTextField jTextField54;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JButton limpa;
    private javax.swing.JTextField nom1;
    private javax.swing.JTextField nome1;
    public javax.swing.JTextField nome2;
    private javax.swing.JTextField nomedisc;
    private javax.swing.JTextField periododisc;
    public static javax.swing.JFormattedTextField rg1;
    private javax.swing.JTextField rg3;
    private javax.swing.JTextField rgdis;
    private javax.swing.JFormattedTextField rgt;
    private javax.swing.JTextField saladisc;
    private javax.swing.JButton salvar1;
    public javax.swing.JTextField sobrenome1;
    private javax.swing.JTextField sobrenome2;
    private javax.swing.JTextField sobrenomedisc;
    private javax.swing.JTextField turmadisc;
    // End of variables declaration//GEN-END:variables
}
